import type { Metadata } from "next";

import "./globals.css";

import BgImage from "@/components/layout/BgImage";
import Ui from "@/components/layout/Ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className=" bg-black relative w-full overflow-hidden">
        <div className="flex">
          <Ui />
          {children}
        </div>
        <BgImage />
      </body>
    </html>
  );
}
